spring:
  application:
    name: DEPARTMENT-SERVICE
server:
  port: 9091

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
     localhost: localhost
    #instance-id: '${spring.application.name}-${random.int}'
